### ISSUE TITLE
Has Problem when library(CtyoTree)

### ISSUE THREAD

**Issue by aimer-entropy** [JhuangLab/CytoTree#1]
When I run library(CtyoTree), it shows me this,

No methods found in package ‘flowCore’ for requests: ‘action’, ‘assign’, ‘Data’, ‘gate’, ‘tree’ when loading ‘flowUtils’

Does this interferes with my usage of this package?

**Comment by ytdai** [comment]
> When I run library(CtyoTree), it shows me this,
> 
> No methods found in package ‘flowCore’ for requests: ‘action’, ‘assign’, ‘Data’, ‘gate’, ‘tree’ when loading ‘flowUtils’
> 
> Does this interferes with my usage of this package?

No, it doesn't affect the usage.

**Comment by aimer-entropy** [comment]
> > When I run library(CtyoTree), it shows me this,
> > No methods found in package ‘flowCore’ for requests: ‘action’, ‘assign’, ‘Data’, ‘gate’, ‘tree’ when loading ‘flowUtils’
> > Does this interferes with my usage of this package?
> 
> No, it doesn't affect the usage.

Thanks for the reply.
