### ISSUE TITLE
Is CytoTree a deprecated package on Bioconductor 3.16?

### ISSUE THREAD

**Issue by zoqaiyum** [JhuangLab/CytoTree#11]
Hello, 

I was trying to download CytoTree and flowUtils (which is a related package for CytoTree). However, I am unable to download both packages. Upon further inspection, I noticed that both these packages are deprecated from Bioconductor (https://support.bioconductor.org/p/9147242/). Are you coming up with an alternative to CytoTree by any chance? I really would like to use it for my analysis. Thanks.

**Comment by nmahanna** [comment]
I am also a huge fan of the package and would hate to see it removed from Bioconductor. It is a great piece of work with good documentation.

While it is not available through ```Biocmanager::install('Cytotree')``` any longer it can still be downloaded from GitHub. 
```devtools::install_github("JhuangLab/CytoTree")```

However installing Cytotree from GitHub still requires the package _flowUtils_ which has also been deprecated from Bioconductor. I had to download and install the binary from the Bioconductor [3.15 webpage ](https://www.bioconductor.org/packages/3.15/bioc/html/flowUtils.html). Then install _Cytotree_ through Github. 

It would be great if _Cytotree_ did not import _flowUtils_ then it would be remain available through Github regardless of its Bioc status. Not sure the odds of it being updated are - I will most likely finish up with Cytotree and migrate over to conducting my flow analysis with _flowSOM_ and _CATALYST_.

**Comment by ytdai** [comment]
The CytoTree package depends on a large number of external packages. I plan to restructure it and update a new version.
