### ISSUE TITLE
can't run createCYT without meta.data

### ISSUE THREAD

**Issue by hmf0103** [JhuangLab/CytoTree#7]
Hi. I have been following your tutorial but the function of createCYT in the tutorial is different from the quick start. Many parts that call createCYT like below actually can't run because the lack of meta.data.
# Build the CYT object
cyt <- createCYT(raw.data = fcs.data, normalization.method = "log")
# returns
Error in createCYT(raw.data = cyt.data, normalization.method = "none") :  meta.data must be a data.frame

**Comment by immuen** [comment]
I am currently facing the same problem. CytoTree cannot create a CYT without metadata (that I do not know of where it should come from) on my case neither. Do you maybe have an update on that? : Br,

**Comment by ytdai** [comment]
Sorry for the late reply. It is recommended to re-install CytoTree via github. Thank you!
